# ==========================================
# 1. Global & Core Configuration
# ==========================================
gfx-api = "Vulkan"
#repeat-rate = { rate = 50, delay = 200 }
use-hardware-cursor = true
focus-follows-mouse = false
middle-click-paste = false
workspace-display-order = "sorted"
fallback-output-mode = "focus"
explicit-sync = true
show-titles = false
show-bar = false

render-device.name = "nvidia"

window-management-key = "Super_L" 

# --- Startup Hooks ---
on-graphics-initialized = [
    { type = "exec", exec = "gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'" },
    { type = "exec", exec = "gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'" },
    { type = "exec", exec = "waybar", privileged = true },
    { type = "exec", exec = "ghostty" },
    { type = "exec", exec = "swaync" },
    { type = "exec", exec = "awww-daemon", privileged = true },
    { type = "exec", exec = { prog = "zsh", args = ["-c", "sleep 1 && awww img /home/xv/Downloads/train-sideview.png"] } },
    { type = "exec", exec = { prog = "swayidle", args = ["-w", "timeout", "900", "swaylock -f", "before-sleep", "swaylock -f"], privileged = true } },

   # XF86AudioRaiseVolume = { type = "exec", exec = ["pactl", "set-sink-volume", "0", "+5%"] }
   # XF86AudioLowerVolume = { type = "exec", exec = ["pactl", "set-sink-volume", "0", "-5%"]}
   # XF86AudioMute = { type = "exec",exec = ["pactl", "set-sink-mute", "0", "toggle"] }

# Bind workspaces to outputs on startup
    { type = "show-workspace", name = "1", output.name = "Main", move-to-output = true },
]

# ==========================================
# 2. Theme
# ==========================================
[theme]
border-width = 2
container-borders = "full"
border-color = "#FFFFFF00"
bar-separator-width = 1
separator-color = "#350030"
bg-color = "#000000"
focused-title-bg-color = "#350030"
focused-title-text-color = "#EEEEEE"
unfocused-title-bg-color = "#000000"
unfocused-title-text-color = "#999999"
focused-inactive-title-bg-color = "#250015"
focused-inactive-title-text-color = "#999999"
focused-border-color = "#1A1B26"
workspace-display-order = "sorted"


# ==========================================
# 3. Hardware & Devices
# ==========================================
[[drm-devices]]
name = "nvidia"
match = { pci-vendor = 0x10de, pci-model = 0x2d05 }

[[drm-devices]]
name = "intel"
match = { pci-vendor = 0x8086, pci-model = 0xa780 }

[[inputs]]
match.is-pointer = true
accel-profile = "flat"
accel-speed = -0.9600
natural-scrolling = false

[[inputs]]
match.syspath = "/sys/devices/pci0000:00/0000:00:15.1/i2c_designware.1/i2c-4/i2c-ELAN0A02:01"
accel-profile = "flat"
accel-speed = 0.36
natural-scrolling = true
tap-enabled = true



# ==========================================
# 4. Outputs (Monitors)
# ==========================================
[[outputs]]
name = "Main"
match = { connector = "eDP-1" }
x = 0
y = 0
mode = { width = 1920, height = 1080, refresh-rate = 144.000 }
tearing.mode = "always"

# ==========================================
# 5. Shortcuts
# ==========================================
[shortcuts]
logo-Return   = { type = "exec", exec = "ghostty" }
logo-p        = { type = "exec", exec = "fuzzel" }
logo-shift-s  = { type = "exec", exec = { prog = "zsh", args = ["-lc", "wayfreeze --after-freeze-cmd 'grim -g \"$(slurp)\" - | wl-copy; killall wayfreeze'"], privileged = true } }
logo-x =        { type = "exec", exec = { prog = "zsh", args = ["-c", "swaync-client -t -sw"] } }

logo-q            = "close"
logo-f            = "toggle-fullscreen"
logo-shift-q      = "quit"
logo-shift-r      = "reload-config-toml"
logo-shift-space  = "toggle-floating"
XF86AudioLowerVolume = { type = "exec", exec = {shell = "amixer set Master 5%-"}}
XF86AudioRaiseVolume = { type = "exec", exec = {shell = "amixer set Master 5%+"}}



# Workspace Switching
logo-1 = [ { type = "show-workspace", name = "1" }, "focus-tiles", "warp-mouse-to-focus" ]
logo-2 = [ { type = "show-workspace", name = "2" }, "focus-tiles", "warp-mouse-to-focus" ]
logo-3 = [ { type = "show-workspace", name = "3" }, "focus-tiles", "warp-mouse-to-focus" ]
logo-4 = [ { type = "show-workspace", name = "4" }, "focus-tiles", "warp-mouse-to-focus" ]
logo-5 = [ { type = "show-workspace", name = "5" }, "focus-tiles", "warp-mouse-to-focus" ]
logo-6 = [ { type = "show-workspace", name = "6" }, "focus-tiles", "warp-mouse-to-focus" ]
logo-7 = [ { type = "show-workspace", name = "7" }, "focus-tiles", "warp-mouse-to-focus" ]
logo-8 = [ { type = "show-workspace", name = "8" }, "focus-tiles", "warp-mouse-to-focus" ]
logo-9 = [ { type = "show-workspace", name = "9" }, "focus-tiles", "warp-mouse-to-focus" ]
logo-0 = [ { type = "show-workspace", name = "10" }, "focus-tiles", "warp-mouse-to-focus" ]


# Move Window & Follow
logo-shift-1 = [ { type = "move-to-workspace", name = "1" }, { type = "show-workspace", name = "1" }, "warp-mouse-to-focus" ]
logo-shift-2 = [ { type = "move-to-workspace", name = "2" }, { type = "show-workspace", name = "2" }, "warp-mouse-to-focus" ]
logo-shift-3 = [ { type = "move-to-workspace", name = "3" }, { type = "show-workspace", name = "3" }, "warp-mouse-to-focus" ]
logo-shift-4 = [ { type = "move-to-workspace", name = "4" }, { type = "show-workspace", name = "4" }, "warp-mouse-to-focus" ]
logo-shift-5 = [ { type = "move-to-workspace", name = "5" }, { type = "show-workspace", name = "5" }, "warp-mouse-to-focus" ]
logo-shift-6 = [ { type = "move-to-workspace", name = "6" }, { type = "show-workspace", name = "6" }, "warp-mouse-to-focus" ]
logo-shift-7 = [ { type = "move-to-workspace", name = "7" }, { type = "show-workspace", name = "7" }, "warp-mouse-to-focus" ]
logo-shift-8 = [ { type = "move-to-workspace", name = "8" }, { type = "show-workspace", name = "8" }, "warp-mouse-to-focus" ]
logo-shift-9 = [ { type = "move-to-workspace", name = "9" }, { type = "show-workspace", name = "9" }, "warp-mouse-to-focus" ]
logo-shift-0 = [ { type = "move-to-workspace", name = "10" }, { type = "show-workspace", name = "10" }, "warp-mouse-to-focus" ]

# Directional focus-vim

logo-h = [ "focus-tiles", "focus-left", "warp-mouse-to-focus" ]
logo-j = [ "focus-tiles", "focus-down", "warp-mouse-to-focus" ]
logo-k = [ "focus-tiles", "focus-up", "warp-mouse-to-focus" ]
logo-l = [ "focus-tiles", "focus-right", "warp-mouse-to-focus" ]

# Directional focus-arrow

logo-Left  = [ "focus-tiles", "focus-left", "warp-mouse-to-focus" ]
logo-Down  = [ "focus-tiles", "focus-down", "warp-mouse-to-focus" ]
logo-Up    = [ "focus-tiles", "focus-up", "warp-mouse-to-focus" ]
logo-Right = [ "focus-tiles", "focus-right", "warp-mouse-to-focus" ]

# Change tty
ctrl-alt-F1 = { type = "switch-to-vt", num = 1 }
ctrl-alt-F2 = { type = "switch-to-vt", num = 2 }
ctrl-alt-F3 = { type = "switch-to-vt", num = 3 }
ctrl-alt-F4 = { type = "switch-to-vt", num = 4 }
ctrl-alt-F5 = { type = "switch-to-vt", num = 5 }
ctrl-alt-F6 = { type = "switch-to-vt", num = 6 }
ctrl-alt-F7 = { type = "switch-to-vt", num = 7 }
ctrl-alt-F8 = { type = "switch-to-vt", num = 8 }
ctrl-alt-F9 = { type = "switch-to-vt", num = 9 }
ctrl-alt-F10 = { type = "switch-to-vt", num = 10 }
ctrl-alt-F11 = { type = "switch-to-vt", num = 11 }
ctrl-alt-F12 = { type = "switch-to-vt", num = 12 }



# ==========================================
# 6. Rules & Capabilities
# ==========================================
# [[windows]]
# match = { any = [
#     { app-id = "discord" },
#     { app-id = "spotify" },
#     { app-id = "com.obsproject.Studio" },
# ] }
# action = [ { type = "move-to-output", output = "Secondary" } ]

[[windows]]
match = { any = [
    { app-id = "zen", title = "Picture-in-Picture" },
    { app-id = "firefox", title = "Picture-in-Picture" }
] }
initial-tile-state = "floating"
#action = [ "pin-float", "toggle-float-above-fullscreen" ]
action = [ "pin-float", "enable-float-above-fullscreen" ]


[[clients]]
match = { exe-regex = "^/usr/bin/waybar$" }
capabilities = [ "layer-shell", "workspace-manager", "foreign-toplevel-manager" ]

[[clients]]
match = { exe-regex = "^/usr/bin/awww-daemon$" }
capabilities = [ "layer-shell" ]

[[clients]]
match = { exe-regex = "^/usr/bin/wl-(copy|paste)$" }
capabilities = [ "data-control" ]

[[clients]]
match.comm = "swaylock"
capabilities = [ "session-lock", "layer-shell" ]
